project               = "gcp-terraform-env"
group                 = "value"
name                  = "cloudrun-neg"
network_endpoint_type = "SERVERLESS"
region                = "us-central1"
image                 = "us-docker.pkg.dev/cloudrun/container/hello"
zone                  = "us-central1-a"
